# Generated by Django 4.0.1 on 2022-02-11 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beatup', '0006_alter_post_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
    ]
