# Generated by Django 4.0.1 on 2022-02-12 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beatup', '0008_alter_post_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['date']},
        ),
    ]
