# Generated by Django 4.0.1 on 2022-02-17 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beatup', '0010_alter_post_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='user_post/'),
        ),
    ]
