# Generated by Django 4.0.1 on 2022-02-25 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beatup', '0012_alter_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='famous',
            field=models.BooleanField(default=0),
        ),
    ]
