# Generated by Django 4.0.1 on 2022-02-25 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beatup', '0013_customer_famous'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='famous',
            field=models.BooleanField(default=True),
        ),
    ]
